/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IcareAvatar {
    }
    interface IcareButton {
        /**
          * @default 'Click'
         */
        "label": string;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary';
    }
    interface IcareCard {
        /**
          * @default false
         */
        "interactive": boolean;
        /**
          * @default 'outlined'
         */
        "variant": 'elevated' | 'outlined';
    }
    interface IcareCaregiverProfileCard {
        "cardTitle": string;
        "description": string;
        /**
          * @default []
         */
        "features": string[];
        "imageAlt": string;
        "imageSrc": string;
        "shortBio": string;
    }
    interface IcareHeader {
        /**
          * @default false
         */
        "loggedIn": boolean;
    }
    interface IcareHero {
        /**
          * Alt text for accessibility
          * @default 'iCare hero image'
         */
        "imageAlt": string;
        /**
          * Background hero image source
          * @default 'images/heros/hero-landing-page.jpg'
         */
        "imageSrc": string;
        /**
          * Overlay position: 'top', 'center', 'bottom'
          * @default 'center'
         */
        "overlayPosition": 'top' | 'center' | 'bottom';
    }
    interface IcareLogo {
    }
    interface IcarePage {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLIcareAvatarElement extends Components.IcareAvatar, HTMLStencilElement {
    }
    var HTMLIcareAvatarElement: {
        prototype: HTMLIcareAvatarElement;
        new (): HTMLIcareAvatarElement;
    };
    interface HTMLIcareButtonElement extends Components.IcareButton, HTMLStencilElement {
    }
    var HTMLIcareButtonElement: {
        prototype: HTMLIcareButtonElement;
        new (): HTMLIcareButtonElement;
    };
    interface HTMLIcareCardElement extends Components.IcareCard, HTMLStencilElement {
    }
    var HTMLIcareCardElement: {
        prototype: HTMLIcareCardElement;
        new (): HTMLIcareCardElement;
    };
    interface HTMLIcareCaregiverProfileCardElement extends Components.IcareCaregiverProfileCard, HTMLStencilElement {
    }
    var HTMLIcareCaregiverProfileCardElement: {
        prototype: HTMLIcareCaregiverProfileCardElement;
        new (): HTMLIcareCaregiverProfileCardElement;
    };
    interface HTMLIcareHeaderElement extends Components.IcareHeader, HTMLStencilElement {
    }
    var HTMLIcareHeaderElement: {
        prototype: HTMLIcareHeaderElement;
        new (): HTMLIcareHeaderElement;
    };
    interface HTMLIcareHeroElement extends Components.IcareHero, HTMLStencilElement {
    }
    var HTMLIcareHeroElement: {
        prototype: HTMLIcareHeroElement;
        new (): HTMLIcareHeroElement;
    };
    interface HTMLIcareLogoElement extends Components.IcareLogo, HTMLStencilElement {
    }
    var HTMLIcareLogoElement: {
        prototype: HTMLIcareLogoElement;
        new (): HTMLIcareLogoElement;
    };
    interface HTMLIcarePageElement extends Components.IcarePage, HTMLStencilElement {
    }
    var HTMLIcarePageElement: {
        prototype: HTMLIcarePageElement;
        new (): HTMLIcarePageElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "icare-avatar": HTMLIcareAvatarElement;
        "icare-button": HTMLIcareButtonElement;
        "icare-card": HTMLIcareCardElement;
        "icare-caregiver-profile-card": HTMLIcareCaregiverProfileCardElement;
        "icare-header": HTMLIcareHeaderElement;
        "icare-hero": HTMLIcareHeroElement;
        "icare-logo": HTMLIcareLogoElement;
        "icare-page": HTMLIcarePageElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface IcareAvatar {
    }
    interface IcareButton {
        /**
          * @default 'Click'
         */
        "label"?: string;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary';
    }
    interface IcareCard {
        /**
          * @default false
         */
        "interactive"?: boolean;
        /**
          * @default 'outlined'
         */
        "variant"?: 'elevated' | 'outlined';
    }
    interface IcareCaregiverProfileCard {
        "cardTitle"?: string;
        "description"?: string;
        /**
          * @default []
         */
        "features"?: string[];
        "imageAlt"?: string;
        "imageSrc"?: string;
        "shortBio"?: string;
    }
    interface IcareHeader {
        /**
          * @default false
         */
        "loggedIn"?: boolean;
    }
    interface IcareHero {
        /**
          * Alt text for accessibility
          * @default 'iCare hero image'
         */
        "imageAlt"?: string;
        /**
          * Background hero image source
          * @default 'images/heros/hero-landing-page.jpg'
         */
        "imageSrc"?: string;
        /**
          * Overlay position: 'top', 'center', 'bottom'
          * @default 'center'
         */
        "overlayPosition"?: 'top' | 'center' | 'bottom';
    }
    interface IcareLogo {
    }
    interface IcarePage {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "icare-avatar": IcareAvatar;
        "icare-button": IcareButton;
        "icare-card": IcareCard;
        "icare-caregiver-profile-card": IcareCaregiverProfileCard;
        "icare-header": IcareHeader;
        "icare-hero": IcareHero;
        "icare-logo": IcareLogo;
        "icare-page": IcarePage;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "icare-avatar": LocalJSX.IcareAvatar & JSXBase.HTMLAttributes<HTMLIcareAvatarElement>;
            "icare-button": LocalJSX.IcareButton & JSXBase.HTMLAttributes<HTMLIcareButtonElement>;
            "icare-card": LocalJSX.IcareCard & JSXBase.HTMLAttributes<HTMLIcareCardElement>;
            "icare-caregiver-profile-card": LocalJSX.IcareCaregiverProfileCard & JSXBase.HTMLAttributes<HTMLIcareCaregiverProfileCardElement>;
            "icare-header": LocalJSX.IcareHeader & JSXBase.HTMLAttributes<HTMLIcareHeaderElement>;
            "icare-hero": LocalJSX.IcareHero & JSXBase.HTMLAttributes<HTMLIcareHeroElement>;
            "icare-logo": LocalJSX.IcareLogo & JSXBase.HTMLAttributes<HTMLIcareLogoElement>;
            "icare-page": LocalJSX.IcarePage & JSXBase.HTMLAttributes<HTMLIcarePageElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
