/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IcareButton {
        /**
          * @default 'Click'
         */
        "label": string;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary';
    }
    interface IcareCaregiverProfileCard {
        "cardTitle": string;
        "description": string;
        /**
          * @default []
         */
        "features": string[];
        "imageAlt": string;
        "imageSrc": string;
        "shortBio": string;
    }
    interface IcareHeader {
        /**
          * @default false
         */
        "loggedIn": boolean;
    }
    interface IcareLogo {
    }
    interface IcarePage {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLIcareButtonElement extends Components.IcareButton, HTMLStencilElement {
    }
    var HTMLIcareButtonElement: {
        prototype: HTMLIcareButtonElement;
        new (): HTMLIcareButtonElement;
    };
    interface HTMLIcareCaregiverProfileCardElement extends Components.IcareCaregiverProfileCard, HTMLStencilElement {
    }
    var HTMLIcareCaregiverProfileCardElement: {
        prototype: HTMLIcareCaregiverProfileCardElement;
        new (): HTMLIcareCaregiverProfileCardElement;
    };
    interface HTMLIcareHeaderElement extends Components.IcareHeader, HTMLStencilElement {
    }
    var HTMLIcareHeaderElement: {
        prototype: HTMLIcareHeaderElement;
        new (): HTMLIcareHeaderElement;
    };
    interface HTMLIcareLogoElement extends Components.IcareLogo, HTMLStencilElement {
    }
    var HTMLIcareLogoElement: {
        prototype: HTMLIcareLogoElement;
        new (): HTMLIcareLogoElement;
    };
    interface HTMLIcarePageElement extends Components.IcarePage, HTMLStencilElement {
    }
    var HTMLIcarePageElement: {
        prototype: HTMLIcarePageElement;
        new (): HTMLIcarePageElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "icare-button": HTMLIcareButtonElement;
        "icare-caregiver-profile-card": HTMLIcareCaregiverProfileCardElement;
        "icare-header": HTMLIcareHeaderElement;
        "icare-logo": HTMLIcareLogoElement;
        "icare-page": HTMLIcarePageElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface IcareButton {
        /**
          * @default 'Click'
         */
        "label"?: string;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary';
    }
    interface IcareCaregiverProfileCard {
        "cardTitle"?: string;
        "description"?: string;
        /**
          * @default []
         */
        "features"?: string[];
        "imageAlt"?: string;
        "imageSrc"?: string;
        "shortBio"?: string;
    }
    interface IcareHeader {
        /**
          * @default false
         */
        "loggedIn"?: boolean;
    }
    interface IcareLogo {
    }
    interface IcarePage {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "icare-button": IcareButton;
        "icare-caregiver-profile-card": IcareCaregiverProfileCard;
        "icare-header": IcareHeader;
        "icare-logo": IcareLogo;
        "icare-page": IcarePage;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "icare-button": LocalJSX.IcareButton & JSXBase.HTMLAttributes<HTMLIcareButtonElement>;
            "icare-caregiver-profile-card": LocalJSX.IcareCaregiverProfileCard & JSXBase.HTMLAttributes<HTMLIcareCaregiverProfileCardElement>;
            "icare-header": LocalJSX.IcareHeader & JSXBase.HTMLAttributes<HTMLIcareHeaderElement>;
            "icare-logo": LocalJSX.IcareLogo & JSXBase.HTMLAttributes<HTMLIcareLogoElement>;
            "icare-page": LocalJSX.IcarePage & JSXBase.HTMLAttributes<HTMLIcarePageElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
